config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  root :to =>"public/homes#top"
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    get 'search' => 'posts#search'
    get 'posts/timeline' => 'posts#index', as: :timeline
    patch 'customers/release' => 'customers#release' , as: :release
    patch 'customers/nonrelease' => 'customers#nonrelease' , as: :nonrelease
    resources :customers, only: [:show,:edit,:update]
    patch 'customers/:id/withdraw' => 'customers#withdraw', as: :withdraw
    resources :tags, only: [:show]
    resources :posts, only: [:new , :create, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      get 'favorites' => 'favorites#favorites' ,as: 'fovorites'
    end
    resources :customers do
      resource :relationships, only: [:show, :create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @customer = Customer.where(params[:id])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<%= stylesheet_pack_tag "homes" %>
<div class="container  shadow-sm" style="width:100%; height:700px; margin-top:30px; background-color:#fff; border-radius:5px;">
  <div class="row">
    <div class="col-12">
      <h3 class="text-center mt-4"><strong>会員一覧</strong></h3>
      <table class="table table-hover table-bordered mt-4">
        <thead>
          <tr>
            <th class="col-3">登録日時</th>
            <th class="col-3">会員名</th>
            <th class="col-3">OOTD ID</th>
            <th class="col-3"></th>
          </tr>
        </thead>
        <tbody>
          <% @customer.each do |customer| %>
          <tr>
          <td><%= customer.created_at %></td>
          <td><%= customer.last_name %><%= customer.first_name %></td>
          <td><%= customer.ootd_id %></td>
          <td>
            <%= link_to "詳細", admin_customer_path(customer.id) ,class:"btn btn-primary" %>
          </td>
          </tr>
          <% end %>
        </tbody>
        </table>
    </div>
  </div>
</div>